version: '3'
services:
  app:
    build: .
    ports:
      - "4000:3400"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db  